import type { BusinessEstimate } from '@/types';

export interface BusinessTemplate {
  key: string;
  label: string;
  icon: string;
  description: string;
  mainProduct: string;
  unitLabel: string;
  startupCosts: { item: string; estimatedCost: number }[];
  monthlyFixedCosts: { item: string; estimatedCost: number }[];
  ingredients: { item: string; estimatedCost: number }[];
  suggestedPriceRange: { min: number; max: number };
  marketingTips: string[];
  marginTips: string[];
}

export const businessTemplates: BusinessTemplate[] = [
  {
    key: 'cafe',
    label: 'Kedai Kopi',
    icon: 'Coffee',
    description: 'Kedai kopi modern dengan minuman berbasis espresso',
    mainProduct: 'Cangkir kopi',
    unitLabel: 'cangkir',
    startupCosts: [
      { item: 'Mesin espresso', estimatedCost: 8000000 },
      { item: 'Grinder biji kopi', estimatedCost: 3000000 },
      { item: 'Peralatan barista (tamper, pitcher, dll)', estimatedCost: 1500000 },
      { item: 'Renovasi & desain interior', estimatedCost: 10000000 },
      { item: 'Furniture (meja, kursi)', estimatedCost: 5000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 1000000 },
      { item: 'Awal stok biji kopi & susu', estimatedCost: 2000000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 3000000 },
      { item: 'Listrik & air', estimatedCost: 800000 },
      { item: 'Gaji barista (1 orang)', estimatedCost: 3000000 },
      { item: 'Internet & POS', estimatedCost: 500000 },
      { item: 'Pemasaran digital', estimatedCost: 500000 },
    ],
    ingredients: [
      { item: 'Biji kopi (per cup)', estimatedCost: 3000 },
      { item: 'Susu (per cup)', estimatedCost: 4000 },
      { item: 'Gula & sirup', estimatedCost: 1000 },
      { item: 'Cup & sedotan', estimatedCost: 1500 },
    ],
    suggestedPriceRange: { min: 18000, max: 25000 },
    marketingTips: [
      'Promo "buy 1 get 1" di jam sepi untuk meningkatkan foot traffic',
      'Buat program loyalty card — beli 10 gratis 1',
      'Aktif di Instagram & TikTok dengan konten behind-the-scenes pembuatan kopi',
      'Kerja sama dengan kantor atau coworking space di sekitar untuk diskon karyawan',
    ],
    marginTips: [
      'Beli biji kopi langsung dari petani/supplier untuk menurunkan harga beli',
      'Tawarkan ukuran "large" dengan margin lebih tinggi untuk upselling',
      'Kurangi pemborosan susu dengan training pour yang tepat',
      'Tambah menu makanan ringan dengan margin tinggi sebagai pelengkap',
    ],
  },
  {
    key: 'burger-stall',
    label: 'Burger Stall',
    icon: 'Sandwich',
    description: 'Stan burger cepat saji untuk takeaway & delivery',
    mainProduct: 'Burger',
    unitLabel: 'burger',
    startupCosts: [
      { item: 'Grill / flat top', estimatedCost: 3500000 },
      { item: 'Peralatan dapur (spatula, kompor, dll)', estimatedCost: 1500000 },
      { item: 'Bakul & etalase', estimatedCost: 1000000 },
      { item: 'Renovasi stan', estimatedCost: 5000000 },
      { item: 'Kulkas kecil', estimatedCost: 2500000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 500000 },
      { item: 'Awal stok bahan', estimatedCost: 1500000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 1500000 },
      { item: 'Listrik & air', estimatedCost: 400000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2500000 },
      { item: 'Pemasaran digital', estimatedCost: 300000 },
    ],
    ingredients: [
      { item: 'Roti burger', estimatedCost: 2000 },
      { item: 'Daging patty', estimatedCost: 8000 },
      { item: 'Keju', estimatedCost: 1500 },
      { item: 'Sayuran (selada, tomat, bawang)', estimatedCost: 1500 },
      { item: 'Saus & mayo', estimatedCost: 1000 },
      { item: 'Kertas pembungkus', estimatedCost: 500 },
    ],
    suggestedPriceRange: { min: 20000, max: 30000 },
    marketingTips: [
      'Daftar di GoFood / GrabFood untuk menjangkau pelanggan delivery',
      'Promo "meal deal" — burger + minuman dengan harga paket',
      'Buat konten TikTok proses memasak burger yang menggugah selera',
      'Promo student discount di dekat sekolah/kampus',
    ],
    marginTips: [
      'Beli daging dalam kemasan besar (bulk) untuk harga per unit lebih murah',
      'Buat combo meal dengan minuman yang margin-nya tinggi',
      'Kurangi waste dengan estimasi stok harian yang akurat',
      'Tawarkan add-on (extra cheese, extra patty) dengan margin 70%+',
    ],
  },
  {
    key: 'laundry',
    label: 'Laundry Service',
    icon: 'WashingMachine',
    description: 'Jasa cuci kering & setrika kiloan',
    mainProduct: 'Kiloan laundry',
    unitLabel: 'kg',
    startupCosts: [
      { item: 'Mesin cuci (2 unit)', estimatedCost: 6000000 },
      { item: 'Mesin pengering', estimatedCost: 4000000 },
      { item: 'Setrika uap & meja setrika', estimatedCost: 2000000 },
      { item: 'Rak jemur & perlengkapan', estimatedCost: 1500000 },
      { item: 'Renovasi tempat', estimatedCost: 3000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 500000 },
      { item: 'Awal stok deterjen', estimatedCost: 1000000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 2000000 },
      { item: 'Listrik & air', estimatedCost: 1200000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2500000 },
      { item: 'Pemasaran digital', estimatedCost: 300000 },
    ],
    ingredients: [
      { item: 'Deterjen (per kg)', estimatedCost: 1500 },
      { item: 'Pelembut (per kg)', estimatedCost: 500 },
      { item: 'Listrika cuci (per kg)', estimatedCost: 1000 },
      { item: 'Plastik pembungkus', estimatedCost: 500 },
    ],
    suggestedPriceRange: { min: 7000, max: 10000 },
    marketingTips: [
      'Tawarkan pickup & delivery gratis untuk area sekitar',
      'Promo "cuci 5 kg gratis 1 kg" untuk pelanggan langganan',
      'Sebarkan brosur di kompleks perumahan & apartemen',
      'Buat program membership bulanan dengan harga khusus',
    ],
    marginTips: [
      'Beli deterjen dalam ukuran galon untuk menurunkan cost per kg',
      'Tawarkan layanan express (4 jam) dengan harga premium',
      'Kombinasikan dengan cuci sepatu / dry cleaning untuk meningkatkan rata-rata transaksi',
      'Optimalkan beban mesin — jangan cuci setengah muatan',
    ],
  },
  {
    key: 'bakery',
    label: 'Toko Roti',
    icon: 'Croissant',
    description: 'Toko roti & kue dengan produksi sendiri',
    mainProduct: 'Roti',
    unitLabel: 'pcs',
    startupCosts: [
      { item: 'Oven', estimatedCost: 5000000 },
      { item: 'Mixer adonan', estimatedCost: 2000000 },
      { item: 'Lemari pendingin display', estimatedCost: 4000000 },
      { item: 'Peralatan baking (loyang, timbangan, dll)', estimatedCost: 2000000 },
      { item: 'Renovasi & etalase', estimatedCost: 6000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 800000 },
      { item: 'Awal stok bahan', estimatedCost: 2000000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 2500000 },
      { item: 'Listrik & gas', estimatedCost: 1000000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2800000 },
      { item: 'Pemasaran digital', estimatedCost: 400000 },
    ],
    ingredients: [
      { item: 'Tepung terigu (per pcs)', estimatedCost: 1500 },
      { item: 'Mentega (per pcs)', estimatedCost: 1000 },
      { item: 'Gula & ragi', estimatedCost: 800 },
      { item: 'Telur (per pcs)', estimatedCost: 700 },
      { item: 'Kertas pembungkus', estimatedCost: 300 },
    ],
    suggestedPriceRange: { min: 5000, max: 8000 },
    marketingTips: [
      'Promo "roti malam" diskon 50% setelah jam 7 malam untuk mengurangi waste',
      'Buat program langganan sarapan — roti fresh setiap pagi',
      'Kerja sama dengan kafe lokal untuk supply roti',
      'Konten Instagram roti fresh dari oven setiap pagi',
    ],
    marginTips: [
      'Beli tepung dalam karung 25 kg untuk harga lebih murah',
      'Produksi roti isi dengan margin lebih tinggi dari roti polos',
      'Manfaatkan sisa adonan untuk produk sampingan (crouton, breadcrumbs)',
      'Tawarkan kue ulang tahun custom dengan margin 60%+',
    ],
  },
  {
    key: 'barbershop',
    label: 'Barbershop',
    icon: 'Scissors',
    description: 'Pangkas rambut pria dengan gaya modern',
    mainProduct: 'Pangkas rambut',
    unitLabel: 'pangkas',
    startupCosts: [
      { item: 'Kursi barbershop (2 unit)', estimatedCost: 4000000 },
      { item: 'Peralatan cukur (clipper, gunting, dll)', estimatedCost: 3000000 },
      { item: 'Cermin & furniture', estimatedCost: 2500000 },
      { item: 'Renovasi & desain interior', estimatedCost: 7000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 500000 },
      { item: 'Awal stok produk', estimatedCost: 1000000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 2500000 },
      { item: 'Listrik & air', estimatedCost: 600000 },
      { item: 'Gaji barber (1 orang)', estimatedCost: 3500000 },
      { item: 'Internet & entertainment', estimatedCost: 400000 },
      { item: 'Pemasaran digital', estimatedCost: 500000 },
    ],
    ingredients: [
      { item: 'Shampoo (per pangkas)', estimatedCost: 1000 },
      { item: 'Hair tonic / pomade', estimatedCost: 2000 },
      { item: 'Alkohol & kapas', estimatedCost: 500 },
      { item: 'Listrik per pangkas', estimatedCost: 500 },
    ],
    suggestedPriceRange: { min: 25000, max: 40000 },
    marketingTips: [
      'Buat program membership — pangkas 10 kali gratis 1',
      'Promo hari Senin-Rabu (jam sepi) dengan harga diskon',
      'Konten before-after di Instagram & TikTok',
      'Kerja sama dengan kafe/sekolah untuk diskon pelanggan',
    ],
    marginTips: [
      'Jual produk pomade/wax dengan margin 50%+ sebagai upselling',
      'Tawarkan layanan grooming (cukur kumis, facial) dengan harga premium',
      'Optimalkan jadwal dengan sistem booking online untuk kurangi waktu kosong',
      'Paket pangkas + cuci rambut dengan margin lebih tinggi',
    ],
  },
  {
    key: 'warung-makan',
    label: 'Warung Makan',
    icon: 'UtensilsCrossed',
    description: 'Warung makan nasi & lauk harian',
    mainProduct: 'Porsi makanan',
    unitLabel: 'porsi',
    startupCosts: [
      { item: 'Kompor & peralatan masak', estimatedCost: 2500000 },
      { item: 'Meja & kursi', estimatedCost: 2000000 },
      { item: 'Peralatan makan (piring, gelas, dll)', estimatedCost: 1500000 },
      { item: 'Renovasi warung', estimatedCost: 3000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 500000 },
      { item: 'Awal stok bahan', estimatedCost: 1500000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 1200000 },
      { item: 'Listrik & air', estimatedCost: 500000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2000000 },
      { item: 'Gas LPG', estimatedCost: 400000 },
    ],
    ingredients: [
      { item: 'Nasi (per porsi)', estimatedCost: 3000 },
      { item: 'Lauk (ayam/ikan)', estimatedCost: 6000 },
      { item: 'Sayur', estimatedCost: 2000 },
      { item: 'Sambal & lauk pelengkap', estimatedCost: 1500 },
      { item: 'Kemasan (kotak plastik)', estimatedCost: 1000 },
    ],
    suggestedPriceRange: { min: 15000, max: 20000 },
    marketingTips: [
      'Promo "paket hemat" nasi + lauk + minuman dengan harga paket',
      'Daftar di GoFood / GrabFood untuk delivery',
      'Buat menu harian yang berganti untuk pelanggan langganan',
      'Promo makan di tempat lebih murah dari takeaway',
    ],
    marginTips: [
      'Beli bahan bahan dari pasar tradisional pagi untuk harga grosir',
      'Masak berdasarkan estimasi penjualan untuk kurangi waste',
      'Tawarkan tambah nasi berbayar dengan margin 90%+',
      'Beli minuman dalam dus besar untuk margin lebih tinggi',
    ],
  },
  {
    key: 'minuman-boba',
    label: 'Minuman Boba',
    icon: 'CupSoda',
    description: 'Stan minuman boba & teh susu',
    mainProduct: 'Cup boba',
    unitLabel: 'cup',
    startupCosts: [
      { item: 'Mesin sealer cup', estimatedCost: 2500000 },
      { item: 'Dispenser air panas & dingin', estimatedCost: 2000000 },
      { item: 'Peralatan masak boba', estimatedCost: 1000000 },
      { item: 'Renovasi stan', estimatedCost: 4000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 500000 },
      { item: 'Awal stok bahan', estimatedCost: 1500000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 1500000 },
      { item: 'Listrik & air', estimatedCost: 400000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2500000 },
      { item: 'Pemasaran digital', estimatedCost: 400000 },
    ],
    ingredients: [
      { item: 'Tepung boba (per cup)', estimatedCost: 2000 },
      { item: 'Susu & krimer', estimatedCost: 3000 },
      { item: 'Teh / sirup', estimatedCost: 1500 },
      { item: 'Cup & sedotan + seal', estimatedCost: 1500 },
      { item: 'Es batu', estimatedCost: 500 },
    ],
    suggestedPriceRange: { min: 12000, max: 18000 },
    marketingTips: [
      'Promo "buy 1 get 1" di jam happy hour (2-4 sore)',
      'Buat varian rasa limited edition setiap bulan',
      'Konten TikTok proses pembuatan boba yang estetik',
      'Promo student discount di dekat sekolah/kampus',
    ],
    marginTips: [
      'Beli boba dalam kemasan besar (1 kg) untuk menurunkan cost per cup',
      'Tawarkan ukuran "large" dengan margin 60%+',
      'Tambah topping (pudding, jelly) dengan margin tinggi sebagai upselling',
      'Kurangi waste es dengan estimasi penjualan yang akurat',
    ],
  },
  {
    key: 'snack-store',
    label: 'Toko Snack',
    icon: 'Cookie',
    description: 'Toko snack kemasan & camilan kering',
    mainProduct: 'Paket snack',
    unitLabel: 'paket',
    startupCosts: [
      { item: 'Rak display', estimatedCost: 2000000 },
      { item: 'Kulkas minuman', estimatedCost: 3000000 },
      { item: 'Kasir & etalase', estimatedCost: 1500000 },
      { item: 'Renovasi toko', estimatedCost: 3000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 500000 },
      { item: 'Awal stok barang', estimatedCost: 5000000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 2000000 },
      { item: 'Listrik & air', estimatedCost: 600000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2500000 },
      { item: 'Pemasaran digital', estimatedCost: 300000 },
    ],
    ingredients: [
      { item: 'Harga beli snack (per paket)', estimatedCost: 8000 },
      { item: 'Kantong plastik', estimatedCost: 200 },
    ],
    suggestedPriceRange: { min: 12000, max: 15000 },
    marketingTips: [
      'Promo "beli 3 lebih murah" untuk mendorong pembelian lebih banyak',
      'Buat rak "promo bulanan" di depan pintu untuk menarik perhatian',
      'Buat paket gift box untuk hari raya / acara khusus',
      'Buat grup WhatsApp pelanggan langganan untuk info stok baru',
    ],
    marginTips: [
      'Beli langsung dari distributor untuk harga grosir lebih murah',
      'Fokus pada produk dengan margin 40%+ dan rotasi cepat',
      'Tawarkan snack combo (3 macam) dengan margin agregat lebih tinggi',
      'Kurangi stok slow-moving dengan promo clearance',
    ],
  },
  {
    key: 'catering',
    label: 'Catering',
    icon: 'Utensils',
    description: 'Jasa catering harian untuk acara & kantor',
    mainProduct: 'Paket catering',
    unitLabel: 'paket',
    startupCosts: [
      { item: 'Peralatan masak profesional', estimatedCost: 5000000 },
      { item: 'Wadah & box catering', estimatedCost: 3000000 },
      { item: 'Kompor industri & oven', estimatedCost: 4000000 },
      { item: 'Kulkas penyimpanan', estimatedCost: 3000000 },
      { item: 'Kendaraan antar', estimatedCost: 15000000 },
      { item: 'Lisensi & izin usaha (PIRT)', estimatedCost: 1000000 },
      { item: 'Awal stok bahan', estimatedCost: 3000000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa dapur', estimatedCost: 2500000 },
      { item: 'Listrik & gas', estimatedCost: 1500000 },
      { item: 'Gaji staf dapur (2 orang)', estimatedCost: 5000000 },
      { item: 'Bensin & transport', estimatedCost: 1000000 },
      { item: 'Pemasaran digital', estimatedCost: 500000 },
    ],
    ingredients: [
      { item: 'Nasi (per paket)', estimatedCost: 4000 },
      { item: 'Lauk ayam/daging (per paket)', estimatedCost: 12000 },
      { item: 'Sayur & sambal', estimatedCost: 3000 },
      { item: 'Kemasan box & sendok', estimatedCost: 2000 },
    ],
    suggestedPriceRange: { min: 25000, max: 35000 },
    marketingTips: [
      'Tawarkan paket langganan harian untuk kantor/swasta',
      'Promo "catering 10 hari gratis 1 hari" untuk pelanggan rutin',
      'Sebarkan brosur ke kompleks perumahan & kantor',
      'Konten Instagram menu harian dengan foto yang menarik',
    ],
    marginTips: [
      'Beli bahan dari pasar grosir pagi buta untuk harga terbaik',
      'Masak dalam batch besar untuk efisiensi bahan bakar',
      'Tawarkan menu upgrade (premium lauk) dengan margin 60%+',
      'Manfaatkan sisa bahan untuk menu internal staf, kurangi waste',
    ],
  },
  {
    key: 'kue-lebaran',
    label: 'Kue Lebaran',
    icon: 'Cake',
    description: 'Produksi kue kering untuk hari raya & harian',
    mainProduct: 'Toples kue',
    unitLabel: 'toples',
    startupCosts: [
      { item: 'Oven kue', estimatedCost: 4000000 },
      { item: 'Mixer adonan', estimatedCost: 1500000 },
      { item: 'Peralatan baking (cutter, loyang, dll)', estimatedCost: 1500000 },
      { item: 'Kemasan toples & pita', estimatedCost: 2000000 },
      { item: 'Renovasi dapur', estimatedCost: 3000000 },
      { item: 'Lisensi & izin usaha (PIRT)', estimatedCost: 500000 },
      { item: 'Awal stok bahan', estimatedCost: 2500000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 1500000 },
      { item: 'Listrik & gas', estimatedCost: 800000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2500000 },
      { item: 'Pemasaran digital', estimatedCost: 500000 },
    ],
    ingredients: [
      { item: 'Tepung & mentega (per toples)', estimatedCost: 15000 },
      { item: 'Gula & telur (per toples)', estimatedCost: 5000 },
      { item: 'Cokelat & topping (per toples)', estimatedCost: 5000 },
      { item: 'Toples & pita', estimatedCost: 3000 },
    ],
    suggestedPriceRange: { min: 45000, max: 65000 },
    marketingTips: [
      'Buka pre-order 1 bulan sebelum Lebaran dengan harga early bird',
      'Buat hampers premium untuk korporat dengan margin tinggi',
      'Konten Instagram & TikTok proses baking yang estetik',
      'Kerja sama dengan agen reseller untuk menjangkau lebih luas',
    ],
    marginTips: [
      'Beli tepung & mentega dalam kemasan grosir 25 kg',
      'Produksi varian premium (kue kering import) dengan margin 70%+',
      'Kurangi waste dengan estimasi pre-order yang akurat',
      'Tawarkan paket combo 3 toples dengan harga bundling',
    ],
  },
  {
    key: 'ayam-geprek',
    label: 'Ayam Geprek',
    icon: 'Drumstick',
    description: 'Stan ayam geprek & nasi pedas',
    mainProduct: 'Porsi ayam geprek',
    unitLabel: 'porsi',
    startupCosts: [
      { item: 'Deep fryer', estimatedCost: 2000000 },
      { item: 'Peralatan dapur (cobek, kompor, dll)', estimatedCost: 1500000 },
      { item: 'Kulkas penyimpanan ayam', estimatedCost: 2500000 },
      { item: 'Renovasi stan', estimatedCost: 4000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 500000 },
      { item: 'Awal stok bahan', estimatedCost: 1500000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 1800000 },
      { item: 'Listrik & air', estimatedCost: 500000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2500000 },
      { item: 'Gas LPG', estimatedCost: 500000 },
      { item: 'Pemasaran digital', estimatedCost: 300000 },
    ],
    ingredients: [
      { item: 'Ayam (per porsi)', estimatedCost: 8000 },
      { item: 'Nasi (per porsi)', estimatedCost: 3000 },
      { item: 'Bumbu geprek (bawang, cabai)', estimatedCost: 2000 },
      { item: 'Tepung & minyak goreng', estimatedCost: 2000 },
      { item: 'Kemasan (box & plastik)', estimatedCost: 1000 },
    ],
    suggestedPriceRange: { min: 18000, max: 25000 },
    marketingTips: [
      'Daftar di GoFood / GrabFood — ayam geprek adalah menu delivery terlaris',
      'Promo "level pedas challenge" untuk konten TikTok viral',
      'Buat paket hemat (geprek + nasi + es teh) dengan harga bundling',
      'Promo buy 2 get 1 di jam sepi untuk boost penjualan',
    ],
    marginTips: [
      'Beli ayam dari supplier langsung (peternak) untuk harga lebih murah',
      'Beli minyak goreng dalam jerigen 20L untuk menurunkan cost per porsi',
      'Tawarkan extra ayam dengan margin 70%+ sebagai upselling',
      'Kurangi waste dengan estimasi penjualan harian yang akurat',
    ],
  },
  {
    key: 'sepatu',
    label: 'Jual Sepatu',
    icon: 'Footprints',
    description: 'Reseller/toko sepatu branded & lokal',
    mainProduct: 'Pasang sepatu',
    unitLabel: 'pasang',
    startupCosts: [
      { item: 'Rak display & etalase', estimatedCost: 3000000 },
      { item: 'Renovasi toko', estimatedCost: 5000000 },
      { item: 'Sistem kasir & POS', estimatedCost: 2000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 500000 },
      { item: 'Awal stok sepatu (20 pasang)', estimatedCost: 10000000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 3000000 },
      { item: 'Listrik & air', estimatedCost: 500000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 3000000 },
      { item: 'Pemasaran digital', estimatedCost: 700000 },
    ],
    ingredients: [
      { item: 'Harga beli sepatu (per pasang)', estimatedCost: 120000 },
      { item: 'Box & kemasan', estimatedCost: 2000 },
    ],
    suggestedPriceRange: { min: 180000, max: 250000 },
    marketingTips: [
      'Jual via marketplace (Tokopedia, Shopee, TikTok Shop)',
      'Konten unboxing & review sepatu di TikTok & Instagram',
      'Promo bundling sepatu + kaos kaki dengan margin tinggi',
      'Buat program membership untuk diskon pembelian berikutnya',
    ],
    marginTips: [
      'Beli stok langsung dari distributor/agen untuk harga grosir',
      'Fokus pada brand dengan margin 40%+ dan turnover cepat',
      'Tawarkan limited edition dengan margin premium',
      'Bersihkan stok slow-moving dengan flash sale',
    ],
  },
  {
    key: 'pulsadantoken',
    label: 'Konter Pulsa',
    icon: 'Smartphone',
    description: 'Konter pulsa, token listrik & top-up e-wallet',
    mainProduct: 'Transaksi pulsa',
    unitLabel: 'transaksi',
    startupCosts: [
      { item: 'Komputer & printer', estimatedCost: 3000000 },
      { item: 'Meja & etalase', estimatedCost: 1500000 },
      { item: 'Renovasi konter', estimatedCost: 2000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 300000 },
      { item: 'Modal deposit distributor', estimatedCost: 5000000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 1500000 },
      { item: 'Listrik & internet', estimatedCost: 600000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2500000 },
    ],
    ingredients: [
      { item: 'Margin per transaksi pulsa', estimatedCost: 0 },
      { item: 'Margin per transaksi token', estimatedCost: 0 },
    ],
    suggestedPriceRange: { min: 1000, max: 2000 },
    marketingTips: [
      'Gabung dengan layanan tambahan: photocopy, print, scan',
      'Buat grup WhatsApp pelanggan langganan untuk top-up otomatis',
      'Promo cashback untuk transaksi token listrik',
      'Tawarkan jasa pendaftaran paket data operator',
    ],
    marginTips: [
      'Naikkan volume transaksi dengan layanan tambahan (print, scan)',
      'Cari distributor pulsa dengan margin lebih tinggi',
      'Tawarkan paket data bundling dengan margin agregat',
      'Kurangi biaya operasional dengan sistem otomatis',
    ],
  },
  {
    key: 'cuci-sepatu',
    label: 'Jasa Cuci Sepatu',
    icon: 'Footprints',
    description: 'Jasa laundry sepatu & sneakers premium',
    mainProduct: 'Pasang sepatu',
    unitLabel: 'pasang',
    startupCosts: [
      { item: 'Mesin cuci khusus sepatu', estimatedCost: 4000000 },
      { item: 'Peralatan cleaning (sikat, cleaner, dll)', estimatedCost: 2000000 },
      { item: 'Rak pengering & display', estimatedCost: 1500000 },
      { item: 'Renovasi tempat', estimatedCost: 3000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 500000 },
      { item: 'Awal stok cleaner', estimatedCost: 1000000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 1800000 },
      { item: 'Listrik & air', estimatedCost: 500000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2500000 },
      { item: 'Pemasaran digital', estimatedCost: 500000 },
    ],
    ingredients: [
      { item: 'Cleaner & shampoo (per pasang)', estimatedCost: 3000 },
      { item: 'Sikat & kain microfiber', estimatedCost: 1000 },
      { item: 'Box & plastik kemasan', estimatedCost: 1500 },
    ],
    suggestedPriceRange: { min: 25000, max: 50000 },
    marketingTips: [
      'Konten before-after sepatu kotor jadi bersih di TikTok & Instagram',
      'Promo "cuci 5 pasang gratis 1 pasang" untuk pelanggan langganan',
      'Kerja sama dengan komunitas sneakerhead & olahraga',
      'Tawarkan pickup & delivery gratis untuk area sekitar',
    ],
    marginTips: [
      'Beli cleaner dalam kemasan galon untuk menurunkan cost per pasang',
      'Tawarkan layanan premium (deep clean, repaint) dengan margin 70%+',
      'Bundling dengan jasa waterproofing dengan margin tinggi',
      'Kurangi waktu proses dengan metode cleaning yang efisien',
    ],
  },
  {
    key: 'donat',
    label: 'Toko Donat',
    icon: 'Donut',
    description: 'Toko donat dengan berbagai topping',
    mainProduct: 'Donat',
    unitLabel: 'pcs',
    startupCosts: [
      { item: 'Deep fryer donat', estimatedCost: 2500000 },
      { item: 'Mixer adonan', estimatedCost: 1500000 },
      { item: 'Display etalase', estimatedCost: 2000000 },
      { item: 'Peralatan (cutter, timbangan, dll)', estimatedCost: 1000000 },
      { item: 'Renovasi toko', estimatedCost: 4000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 500000 },
      { item: 'Awal stok bahan', estimatedCost: 1500000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 2000000 },
      { item: 'Listrik & gas', estimatedCost: 700000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2500000 },
      { item: 'Pemasaran digital', estimatedCost: 400000 },
    ],
    ingredients: [
      { item: 'Tepung terigu (per pcs)', estimatedCost: 1200 },
      { item: 'Mentega & gula (per pcs)', estimatedCost: 800 },
      { item: 'Ragi & telur (per pcs)', estimatedCost: 500 },
      { item: 'Topping (cokelat, meses, dll)', estimatedCost: 1500 },
      { item: 'Box & kertas pembungkus', estimatedCost: 300 },
    ],
    suggestedPriceRange: { min: 5000, max: 8000 },
    marketingTips: [
      'Promo "beli 6 gratis 1" untuk mendorong pembelian lebih banyak',
      'Buat varian topping unik & limited edition tiap bulan',
      'Konten TikTok proses membuat donat yang menarik',
      'Kerja sama dengan kafe/kedai kopi untuk supply donat',
    ],
    marginTips: [
      'Beli tepung dalam karung 25 kg untuk harga lebih murah',
      'Tawarkan donat premium (matcha, tiramisu) dengan margin 60%+',
      'Bundling donat + kopi dengan margin agregat lebih tinggi',
      'Kurangi waste dengan estimasi penjualan harian yang akurat',
    ],
  },
  {
    key: 'es-krim',
    label: 'Stan Es Krim',
    icon: 'IceCream',
    description: 'Stan es krim soft serve & gelato',
    mainProduct: 'Cup es krim',
    unitLabel: 'cup',
    startupCosts: [
      { item: 'Mesin soft serve', estimatedCost: 8000000 },
      { item: 'Freezer展示', estimatedCost: 4000000 },
      { item: 'Peralatan (cone dispenser, scoop, dll)', estimatedCost: 1500000 },
      { item: 'Renovasi stan', estimatedCost: 4000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 500000 },
      { item: 'Awal stok bahan', estimatedCost: 2000000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 2000000 },
      { item: 'Listrik (freezer & mesin)', estimatedCost: 1200000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2500000 },
      { item: 'Pemasaran digital', estimatedCost: 400000 },
    ],
    ingredients: [
      { item: 'Mix es krim (per cup)', estimatedCost: 3000 },
      { item: 'Cone / cup', estimatedCost: 1000 },
      { item: 'Topping (meses, saus, dll)', estimatedCost: 1500 },
    ],
    suggestedPriceRange: { min: 10000, max: 18000 },
    marketingTips: [
      'Promo "buy 1 get 1" di jam happy hour',
      'Buat varian rasa limited edition setiap bulan',
      'Konten Instagram & TikTok es krim yang estetik',
      'Promo student discount di dekat sekolah/kampus',
    ],
    marginTips: [
      'Beli mix es krim dalam kemasan besar untuk menurunkan cost per cup',
      'Tawarkan ukuran "large" dengan margin 60%+',
      'Tambah topping premium dengan margin tinggi sebagai upselling',
      'Kurangi waste dengan estimasi penjualan harian yang akurat',
    ],
  },
  {
    key: 'martabak',
    label: 'Martabak',
    icon: 'Pancake',
    description: 'Stan martabak manis & telur',
    mainProduct: 'Martabak',
    unitLabel: 'pcs',
    startupCosts: [
      { item: 'Kompor & wajan martabak', estimatedCost: 2000000 },
      { item: 'Peralatan dapur (spatula, timbangan, dll)', estimatedCost: 1000000 },
      { item: 'Etalase & meja', estimatedCost: 1500000 },
      { item: 'Renovasi stan', estimatedCost: 3000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 500000 },
      { item: 'Awal stok bahan', estimatedCost: 1500000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 1500000 },
      { item: 'Listrik & gas', estimatedCost: 600000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2500000 },
      { item: 'Pemasaran digital', estimatedCost: 300000 },
    ],
    ingredients: [
      { item: 'Tepung terigu (per pcs)', estimatedCost: 2000 },
      { item: 'Telur & susu (per pcs)', estimatedCost: 3000 },
      { item: 'Topping (cokelat, keju, kacang)', estimatedCost: 5000 },
      { item: 'Mentega & minyak', estimatedCost: 1500 },
      { item: 'Box & kertas', estimatedCost: 500 },
    ],
    suggestedPriceRange: { min: 25000, max: 45000 },
    marketingTips: [
      'Promo "martabak setengah" untuk yang ingin coba 2 rasa',
      'Konten TikTok proses membuat martabak yang menggugah selera',
      'Daftar di GoFood / GrabFood untuk delivery',
      'Promo "buy 2 gratis 1" untuk pembelian malam',
    ],
    marginTips: [
      'Beli tepung & telur dalam kemasan grosir',
      'Tawarkan martabak premium (matcha, tiramisu) dengan margin 60%+',
      'Bundling martabak + minuman dengan margin agregat lebih tinggi',
      'Kurangi waste topping dengan estimasi penjualan yang akurat',
    ],
  },
  {
    key: 'bengkel-motor',
    label: 'Bengkel Motor',
    icon: 'Wrench',
    description: 'Bengkel servis & perbaikan motor',
    mainProduct: 'Servis motor',
    unitLabel: 'servis',
    startupCosts: [
      { item: 'Peralatan bengkel (kunci, dongkrak, dll)', estimatedCost: 5000000 },
      { item: 'Kompressor angin', estimatedCost: 3000000 },
      { item: 'Meja kerja & rak sparepart', estimatedCost: 2500000 },
      { item: 'Renovasi bengkel', estimatedCost: 3000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 500000 },
      { item: 'Awal stok sparepart & oli', estimatedCost: 5000000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 2000000 },
      { item: 'Listrik & air', estimatedCost: 500000 },
      { item: 'Gaji mekanik (1 orang)', estimatedCost: 3500000 },
      { item: 'Pemasaran digital', estimatedCost: 300000 },
    ],
    ingredients: [
      { item: 'Oli & filter (per servis)', estimatedCost: 25000 },
      { item: 'Sparepart konsumsi (per servis)', estimatedCost: 10000 },
      { item: 'Listrik & consumables', estimatedCost: 2000 },
    ],
    suggestedPriceRange: { min: 50000, max: 80000 },
    marketingTips: [
      'Buat program servis berkala — servis 5 kali gratis 1',
      'Promo "servis + ganti oli" dengan harga paket',
      'Sebarkan brosur di kompleks perumahan & area parkir motor',
      'Konten TikTok tips merawat motor untuk membangun trust',
    ],
    marginTips: [
      'Beli oli & sparepart dari distributor besar untuk harga lebih murah',
      'Tawarkan layanan premium (tune-up, modifikasi) dengan margin 60%+',
      'Bundling servis + cuci motor dengan margin agregat',
      'Jual aksesoris motor (helm, cover) dengan margin 50%+',
    ],
  },
  {
    key: 'toko-kelontong',
    label: 'Toko Kelontong',
    icon: 'Store',
    description: 'Toko semboko & kebutuhan harian',
    mainProduct: 'Transaksi',
    unitLabel: 'transaksi',
    startupCosts: [
      { item: 'Rak & etalase', estimatedCost: 3000000 },
      { item: 'Kulkas minuman', estimatedCost: 3000000 },
      { item: 'Sistem kasir & POS', estimatedCost: 1500000 },
      { item: 'Renovasi toko', estimatedCost: 2500000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 300000 },
      { item: 'Awal stok barang', estimatedCost: 10000000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 2000000 },
      { item: 'Listrik & air', estimatedCost: 700000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2500000 },
    ],
    ingredients: [
      { item: 'Harga beli rata-rata (per transaksi)', estimatedCost: 15000 },
      { item: 'Kantong plastik', estimatedCost: 200 },
    ],
    suggestedPriceRange: { min: 17000, max: 22000 },
    marketingTips: [
      'Promo "beli 10 gratis 1" untuk produk fast-moving',
      'Tawarkan layanan delivery gratis untuk area sekitar',
      'Buat program tabungan untuk pelanggan langganan',
      'Tambah layanan pembayaran digital (QRIS) untuk kemudahan',
    ],
    marginTips: [
      'Beli dari grosir / agen besar untuk harga lebih murah',
      'Fokus pada produk dengan margin 25%+ dan rotasi cepat',
      'Tawarkan paket bundling (sembako + minuman) dengan margin agregat',
      'Kurangi stok slow-moving dengan promo clearance',
    ],
  },
  {
    key: 'jasa-cetak',
    label: 'Jasa Cetak',
    icon: 'Printer',
    description: 'Jasa cetak dokumen & foto',
    mainProduct: 'Lembar cetak',
    unitLabel: 'lembar',
    startupCosts: [
      { item: 'Printer inkjet & laser', estimatedCost: 6000000 },
      { item: 'Komputer & desain', estimatedCost: 4000000 },
      { item: 'Mesin fotokopi', estimatedCost: 5000000 },
      { item: 'Meja & rak', estimatedCost: 1500000 },
      { item: 'Renovasi tempat', estimatedCost: 2000000 },
      { item: 'Lisensi & izin usaha', estimatedCost: 300000 },
      { item: 'Awal stok kertas & tinta', estimatedCost: 2000000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 2000000 },
      { item: 'Listrik & internet', estimatedCost: 800000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2800000 },
      { item: 'Pemasaran digital', estimatedCost: 300000 },
    ],
    ingredients: [
      { item: 'Kertas (per lembar)', estimatedCost: 200 },
      { item: 'Tinta & toner (per lembar)', estimatedCost: 300 },
    ],
    suggestedPriceRange: { min: 500, max: 1500 },
    marketingTips: [
      'Promo "cetak 100 lembar gratis 10" untuk pelanggan langganan',
      'Tawarkan jasa desain undangan & banner dengan margin tinggi',
      'Kerja sama dengan sekolah & kampus untuk cetak tugas',
      'Tambah layanan laminating & jilid untuk meningkatkan rata-rata transaksi',
    ],
    marginTips: [
      'Beli kertas dalam rim besar untuk harga lebih murah',
      'Tawarkan paket cetak premium (photo paper, banner) dengan margin 60%+',
      'Bundling cetak + desain dengan margin agregat lebih tinggi',
      'Kurangi waste tinta dengan pengaturan print yang efisien',
    ],
  },
  {
    key: 'keripik',
    label: 'Produksi Keripik',
    icon: 'Package',
    description: 'Produksi keripik & camilan kering untuk reseller',
    mainProduct: 'Bungkus keripik',
    unitLabel: 'bungkus',
    startupCosts: [
      { item: 'Deep fryer industri', estimatedCost: 3000000 },
      { item: 'Mixer & pengaduk', estimatedCost: 1500000 },
      { item: 'Mesin sealers', estimatedCost: 1500000 },
      { item: 'Peralatan dapur', estimatedCost: 1000000 },
      { item: 'Renovasi dapur produksi', estimatedCost: 3000000 },
      { item: 'Lisensi & izin usaha (PIRT)', estimatedCost: 500000 },
      { item: 'Awal stok bahan & kemasan', estimatedCost: 2000000 },
    ],
    monthlyFixedCosts: [
      { item: 'Sewa tempat', estimatedCost: 1500000 },
      { item: 'Listrik & gas', estimatedCost: 1000000 },
      { item: 'Gaji staf (1 orang)', estimatedCost: 2500000 },
      { item: 'Pemasaran digital', estimatedCost: 500000 },
    ],
    ingredients: [
      { item: 'Bahan baku (per bungkus)', estimatedCost: 3000 },
      { item: 'Minyak goreng (per bungkus)', estimatedCost: 1000 },
      { item: 'Bumbu & seasoning (per bungkus)', estimatedCost: 500 },
      { item: 'Kemasan plastik & label', estimatedCost: 500 },
    ],
    suggestedPriceRange: { min: 8000, max: 12000 },
    marketingTips: [
      'Jual via marketplace (Tokopedia, Shopee, TikTok Shop)',
      'Cari reseller & agen di berbagai kota untuk menjangkau lebih luas',
      'Konten TikTok proses produksi yang menarik & "behind the scenes"',
      'Promo "beli 10 gratis 2" untuk pembelian grosir',
    ],
    marginTips: [
      'Beli bahan baku dalam kemasan grosir (karung 50 kg)',
      'Produksi varian premium (keripik pedas, keju) dengan margin 60%+',
      'Bundling beberapa rasa dalam paket gift box dengan margin lebih tinggi',
      'Optimalkan batch produksi untuk efisiensi minyak & gas',
    ],
  },
];

export function findTemplate(key: string): BusinessTemplate | undefined {
  return businessTemplates.find((t) => t.key === key);
}

export function generateEstimate(template: BusinessTemplate): BusinessEstimate {
  const genId = () => Math.random().toString(36).substring(2, 11);

  return {
    startupCosts: template.startupCosts.map((c) => ({ ...c, id: genId() })),
    monthlyFixedCosts: template.monthlyFixedCosts.map((c) => ({ ...c, id: genId() })),
    ingredients: template.ingredients.map((c) => ({ ...c, id: genId() })),
    suggestedPriceRange: { ...template.suggestedPriceRange },
    mainProduct: template.mainProduct,
    unitLabel: template.unitLabel,
  };
}

export function generateCustomEstimate(businessType: string): BusinessEstimate {
  const genId = () => Math.random().toString(36).substring(2, 11);
  const lower = businessType.toLowerCase();

  const matched = businessTemplates.find(
    (t) =>
      lower.includes(t.key) ||
      lower.includes(t.label.toLowerCase()) ||
      t.key.split('-').some((word) => lower.includes(word)),
  );

  if (matched) {
    return generateEstimate(matched);
  }

  return {
    startupCosts: [
      { id: genId(), item: 'Peralatan utama', estimatedCost: 3000000 },
      { id: genId(), item: 'Renovasi tempat', estimatedCost: 4000000 },
      { id: genId(), item: 'Lisensi & izin usaha', estimatedCost: 500000 },
      { id: genId(), item: 'Awal stok bahan', estimatedCost: 1500000 },
    ],
    monthlyFixedCosts: [
      { id: genId(), item: 'Sewa tempat', estimatedCost: 2000000 },
      { id: genId(), item: 'Listrik & air', estimatedCost: 600000 },
      { id: genId(), item: 'Gaji staf (1 orang)', estimatedCost: 2500000 },
      { id: genId(), item: 'Pemasaran', estimatedCost: 400000 },
    ],
    ingredients: [
      { id: genId(), item: 'Bahan baku utama (per unit)', estimatedCost: 8000 },
      { id: genId(), item: 'Kemasan', estimatedCost: 1500 },
    ],
    suggestedPriceRange: { min: 15000, max: 25000 },
    mainProduct: businessType.trim() || 'Produk',
    unitLabel: 'unit',
  };
}
